import { useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check } from "lucide-react";
import { Signal } from "@/components/SignalCard";

import { Recommendation } from "@/hooks/useCallSimulation";

const serviceNames: Record<string, string> = {
  mental: "Mental Health",
  restore: "Physiotherapy / Restore",
  nutrition: "Nutrition",
  vault: "Private Training / Vault",
  forge: "Community / Forge",
};

interface CrmCopyButtonProps {
  signals: Signal[];
  recommendations: Recommendation[];
}

function formatForCrm(signals: Signal[], recommendations: Recommendation[]): string {
  const lines: string[] = [];

  lines.push("═══ HB+ Call Intelligence Summary ═══");
  lines.push("");

  if (signals.length > 0) {
    lines.push("▸ DETECTED SIGNALS");
    lines.push("─────────────────────");
    signals.forEach((s) => {
      const bar = "█".repeat(Math.round(s.intensity / 10)) + "░".repeat(10 - Math.round(s.intensity / 10));
      lines.push(`• ${s.label} [${bar}] ${s.intensity}%`);
      lines.push(`  ${s.description}`);
    });
    lines.push("");
  }

  if (recommendations.length > 0) {
    lines.push("▸ RECOMMENDED SERVICES");
    lines.push("─────────────────────");
    recommendations.forEach((rec, i) => {
      const name = serviceNames[rec.service] ?? rec.service;
      if (i > 0) lines.push("");
      lines.push(`${i + 1}. ${name} — ${rec.confidence}% fit`);
      lines.push(`   Why: ${rec.reason}`);
      lines.push(`   Approach: "${rec.suggestedApproach}"`);
    });
  }

  lines.push("");
  lines.push("─────────────────────");
  lines.push("Generated by HB+ Call Intelligence");

  return lines.join("\n");
}

export function CrmCopyButton({ signals, recommendations }: CrmCopyButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    const text = formatForCrm(signals, recommendations);
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [signals, recommendations]);

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleCopy}
      className="gap-2 text-xs border-sage/30 hover:bg-sage-light hover:text-sage"
    >
      {copied ? (
        <>
          <Check className="h-3.5 w-3.5" />
          Copied for CRM
        </>
      ) : (
        <>
          <Copy className="h-3.5 w-3.5" />
          Copy for CRM
        </>
      )}
    </Button>
  );
}
