import { useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check } from "lucide-react";
import { Signal } from "@/components/SignalCard";

interface Recommendation {
  service: string;
  confidence: number;
  reason: string;
  suggestedApproach: string;
}

const serviceNames: Record<string, string> = {
  mental: "Mental Health",
  restore: "Physiotherapy / Restore",
  nutrition: "Nutrition",
  vault: "Private Training / Vault",
  forge: "Community / Forge",
};

interface CrmCopyButtonProps {
  signals: Signal[];
  recommendation: Recommendation | null;
}

function formatForCrm(signals: Signal[], recommendation: Recommendation | null): string {
  const lines: string[] = [];

  lines.push("═══ HB+ Call Intelligence Summary ═══");
  lines.push("");

  if (signals.length > 0) {
    lines.push("▸ DETECTED SIGNALS");
    lines.push("─────────────────────");
    signals.forEach((s) => {
      const bar = "█".repeat(Math.round(s.intensity / 10)) + "░".repeat(10 - Math.round(s.intensity / 10));
      lines.push(`• ${s.label} [${bar}] ${s.intensity}%`);
      lines.push(`  ${s.description}`);
    });
    lines.push("");
  }

  if (recommendation) {
    const name = serviceNames[recommendation.service] ?? recommendation.service;
    lines.push("▸ RECOMMENDED SERVICE");
    lines.push("─────────────────────");
    lines.push(`Service: ${name}`);
    lines.push(`Confidence: ${recommendation.confidence}%`);
    lines.push("");
    lines.push("Why this feels right:");
    lines.push(recommendation.reason);
    lines.push("");
    lines.push("Suggested approach:");
    lines.push(`"${recommendation.suggestedApproach}"`);
  }

  lines.push("");
  lines.push("─────────────────────");
  lines.push("Generated by HB+ Call Intelligence");

  return lines.join("\n");
}

export function CrmCopyButton({ signals, recommendation }: CrmCopyButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    const text = formatForCrm(signals, recommendation);
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [signals, recommendation]);

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleCopy}
      className="gap-2 text-xs border-sage/30 hover:bg-sage-light hover:text-sage"
    >
      {copied ? (
        <>
          <Check className="h-3.5 w-3.5" />
          Copied for CRM
        </>
      ) : (
        <>
          <Copy className="h-3.5 w-3.5" />
          Copy for CRM
        </>
      )}
    </Button>
  );
}
